### ISSUE TITLE
What is JoBimTextCT?

### ISSUE THREAD

**Issue by jbauer180266** [tudarmstadt-lt/JoBimTextCT#1]
Dear Sir or Madam,

please forgive me for asking such an ignorant question, but: What is JoBimTextCT? I know both JoBim Text and the TU Darmstadt, of course, but I can't clearly figure out what this project is - it also has no description and no Wiki entries. Could you enlighten me, please?

Thank you very much in advance.

Best wishes,
Joe

**Comment by remstef** [comment]
Hi Joe,

JoBimTextCT can be interpreted as the JoBimText hadoop pipeline (w/o holing system) implemented in Spark. It's in an early stage of experimental development, focusing more on the concept of contingency tables as a form of intermediate representation (thus the suffix CT). You might also want to look into the noun-sense-induction-scala project (https://github.com/tudarmstadt-lt/noun-sense-induction-scala) which similarly re-implements the JoBimText pipeline in Spark without focusing on contingency tables. 

Hope I was able to shed some light.

Best, 
Steffen
